whereby/jslib-media

package.json, src/utils/ServerSocket.js
Update to the latest supported socket.io client. This is the same changes as we did in our internal repo, only leaving out the legacy ServerSocket as we dont need that here.
=> Update socket.io client

package.json
We use the `events` pkg in the BandwidthTester and VegaConnection libs, but this dep was not installed directly. It worked as it was installed already because of another package. It's safer to have it in this repo's package.json, so this PR adds it there as a dependency.
<details>
<summary>📦 Published PR as canary version: <code>1.0.4--canary.11.6326145620.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.0.4--canary.11.6326145620.0
yarn add @whereby/jslib-media@1.0.4--canary.11.6326145620.0
```
</details>
=> Add missing events dependency

package.json, src/webrtc/P2pRtcManager.js, src/webrtc/VegaRtcManager.js, tests/webrtc/P2pRtcManager.spec.js, tests/webrtc/VegaRtcManager.spec.js, tests/webrtc/webRtcHelpers.js
Previously, only Chrome needed to stop the video track to make the camera light turn off. Recent Safari releases have now opted to use the same logic, meaning we need to do the same for Safari on our end.
See upcoming PWA PR for test instructions
<details>
<summary>📦 Published PR as canary version: <code>1.0.5--canary.13.6430264587.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.0.5--canary.13.6430264587.0
yarn add @whereby/jslib-media@1.0.5--canary.13.6430264587.0
```
</details>
=> Stop disabled video track when Safari

package.json, src/webrtc/P2pRtcManager.js, src/webrtc/Session.js, src/webrtc/sdpModifier.js
- Add flag for RED RFC2198 codec preference change support
- Set pc null to make sure pc is released after it is closed.
- Bump version
<details>
<summary>📦 Published PR as canary version: <code>1.0.5--canary.14.6429718182.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.0.5--canary.14.6429718182.0
yarn add @whereby/jslib-media@1.0.5--canary.14.6429718182.0
```
</details>
=> Add audio redundancy RED RFC2198 support

package.json, src/utils/constants.js, src/utils/turnConstants.js, src/webrtc/BaseRtcManager.js, src/webrtc/P2pRtcManager.js, src/webrtc/Session.js, src/webrtc/VegaRtcManager.js, src/webrtc/constants.js
Add a jitter buffer delay target of 400 milliseconds for all incoming P2P/SFU audio/video tracks in all RTCRtpReceiver objects.
This feature can be enabled by passing `increaseIncomingMediaBuffer: true` in to `RtcManagerDispatcher` constructor (or directly to `P2pRtcManager` and `VegaRtcManager` constructors). In `pwa` this is handled automatically by adding `?increaseIncomingMediaBuffer` to a room URL and/or by switching on the `increaseIncomingMediaBuffer` feature flag.
---
Prior to this experiement, TestDevLab ran some performance testing and benchmarking against Google Meet.
The charts below show a number of quality metrics over time as packet loss is slowly increased from 0% to 20% and back to 0%. Notice how our delay is non-linear compared to the competitors result:
[Source …
=> Add jitter buffer delay target for all incoming RTCRtpReceiver objects

package.json, src/webrtc/stats/IssueMonitor/index.js, src/webrtc/stats/StatsMonitor/metrics.js
This adds some stats, and distortion issue+metric, for our analysis.
I'm thinking we can regard everything (concealed, removed, inserted) as simply distortion. This can later drive an indicator
Also added fec ratio, to be displayed in !stats overlay
Test it using this PWA PR:
https://github.com/whereby/pwa/pull/3776
<details>
<summary>📦 Published PR as canary version: <code>1.1.2--canary.21.6495986529.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.1.2--canary.21.6495986529.0
yarn add @whereby/jslib-media@1.1.2--canary.21.6495986529.0
```
</details>
=> Adds some audio stats, and distortion issue+metric

package.json
Update `socket.io-client` library dependency from `^4.6.1` to `4.7.2` (removing `^` to force version to be same as that used in our Signal Server).
<details>
<summary>📦 Published PR as canary version: <code>1.2.1--canary.19.6544149237.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.2.1--canary.19.6544149237.0
yarn add @whereby/jslib-media@1.2.1--canary.19.6544149237.0
```
</details>
=> Update socket.io-client to latest (minor) version

package.json, src/webrtc/stats/StatsMonitor/index.js
I've updated the trials by providing feedback, but got the same tokens, so it's just updated expiration date. 
<details>
<summary>📦 Published PR as canary version: <code>1.2.2--canary.22.6545111542.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.2.2--canary.22.6545111542.0
yarn add @whereby/jslib-media@1.2.2--canary.22.6545111542.0
```
</details>
=> Updates compute pressure origin trials

package.json, src/utils/ServerSocket.js
Patch fix to use an absolute path as the default socket.io path in ServerSocket class.
<details>
<summary>📦 Published PR as canary version: <code>1.3.2--canary.25.6572224564.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.3.2--canary.25.6572224564.0
yarn add @whereby/jslib-media@1.3.2--canary.25.6572224564.0
```
</details>
=> Use absolute path in default server socket.io path constant

package.json, src/webrtc/BaseRtcManager.js, src/webrtc/P2pRtcManager.js, src/webrtc/VegaRtcManager.js, tests/webrtc/P2pRtcManager.spec.js, tests/webrtc/VegaRtcManager.spec.js, tests/webrtc/webRtcHelpers.js
Extract all rtc related side-effects of stopping or resuming video into new functions. This allows the existing .stopOrResumeVideo() function to still use this logic, but also allow us to trigger the same logic on the newly introduced `stopresumevideo` event which can be dispatched on the localStream.
The rationale behind this change is to allow our new browser-sdk to get the same side-effects when toggling video, but without maintaining a direct reference to the rtc manager itself.
<details>
<summary>📦 Published PR as canary version: <code>1.3.3--canary.24.6639529096.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.3.3--canary.24.6639529096.0
yarn add @whereby/jslib-media@1.3.3--canary.24.6639529096.0
```
</details>
=> Refactor stopOrResumeVideo, handle localstream event

package.json, yarn.lock
This switches rtcstats to our forked version, getting rid of the chrome error on non whereby.com domains
<details>
<summary>📦 Published PR as canary version: <code>1.3.4--canary.28.6655257686.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.3.4--canary.28.6655257686.0
yarn add @whereby/jslib-media@1.3.4--canary.28.6655257686.0
```
</details>
=> Switches rtcstats to our forked version

package.json, src/webrtc/stats/StatsMonitor/index.js
This adds getUpdatedStats that will collect and return stats immediately (as opposed to subscribing to them and getting it pushed every 2s). Added a throttle to ensure a minimum time between stats comparisons so we don't get 0s if calling a lot inbetween those 2s.
This will be used by PWA for an experiment, detecting if peerConnection/track is in use, to enable a glitch free reconnect to signal. And an immediate remote disconnect seen from PWA if someone leaves the room instead of just being temporarily disconnected from signal.
<details>
<summary>📦 Published PR as canary version: <code>1.3.5--canary.27.6665188085.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.3.5--canary.27.6665188085.0
yarn add …
```
=> Adds getUpdatedStats for immediate stats collection

package.json, src/model/RtcStream.js, src/utils/assert.js, src/webrtc/BaseRtcManager.js, src/webrtc/MediaDevices.js, src/webrtc/VegaRtcManager.js, tests/utils/assert.spec.js, tests/webrtc/MediaDevices.spec.js, tests/webrtc/VegaRtcManager.spec.js, yarn.lock
We have encountered bundle failures on fresh browser-sdk installations with an error message stating, "Could not find module in path: 'assert/assert.js'."
Since we do not heavily depend on this package, we can resolve the issue by replacing the third-party installation.
We will accomplish this by incorporating the relevant assert functions from https://github.com/browserify/commonjs-assert into our repository.
<details>
<summary>📦 Published PR as canary version: <code>1.4.2--canary.32.6769211916.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.4.2--canary.32.6769211916.0
yarn add @whereby/jslib-media@1.4.2--canary.32.6769211916.0
```
</details>
=> Replace the 3rd party `assert` lib

package.json, src/webrtc/P2pRtcManager.js
Removes the cap2pBitrate feature/experiment
<details>
<summary>📦 Published PR as canary version: <code>1.4.3--canary.33.6771611654.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.4.3--canary.33.6771611654.0
yarn add @whereby/jslib-media@1.4.3--canary.33.6771611654.0
```
</details>
=> Removes cap2pBitrate feature

package.json, src/webrtc/rtcStatsService.js
This adds a small buffer for rtcstats getStats. We need it to prevent analysis being broken in some edge cases, like when a new peerConnection's first reports could get lost while being disconnected to rtcstats - along with important initial properties that would never be sent again because of delta compression.
<details>
<summary>📦 Published PR as canary version: <code>1.4.4--canary.34.6809175860.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.4.4--canary.34.6809175860.0
yarn add @whereby/jslib-media@1.4.4--canary.34.6809175860.0
```
</details>
=> Adds small buffer for rtcstats getStats

package.json, src/webrtc/rtcStatsService.js, yarn.lock
This a follow up on https://github.com/whereby/jslib-media/pull/34
This resets delta compression when rtcstats is disconnected. This is needed in some cases when reconnecting to avoid loosing critical stats properties.
To test, watch rtcstats websocket at least 20s (to get 2 sets of getStats reports), dive in and force close it to get a new rtcstats websocket. Compare one of the reports on last getStats on old websocket with first getStats on new websocket. The old would be missing type (among others) property, but the new one should have it beacuse of the delta compression reset
<details>
<summary>📦 Published PR as canary version: <code>1.4.5--canary.35.6822343274.0</code></summary>
<br />
```bash
npm install …
```
=> Resets rtcstats delta compression on disconnect

package.json, src/webrtc/stats/StatsMonitor/index.js
Compute Pressure Origin trial tokens was renewed by sending feedback. Same tokens, but now lasts until Jan 5th. 
The trial was supposed to end after chrome 118, but it is still active and not feature not released yet. We need to continue watching/renewing this
<details>
<summary>📦 Published PR as canary version: <code>1.4.6--canary.38.6981555571.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.4.6--canary.38.6981555571.0
yarn add @whereby/jslib-media@1.4.6--canary.38.6981555571.0
```
</details>
=> Compute pressure tokens renewed

package.json, src/webrtc/stats/IssueMonitor/index.js
This adds a quantization metric, for measuring the effect of some experimental features
<details>
<summary>📦 Published PR as canary version: <code>1.5.2--canary.39.7002480240.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.5.2--canary.39.7002480240.0
yarn add @whereby/jslib-media@1.5.2--canary.39.7002480240.0
```
</details>
=> Tracks quantization metric

package.json, src/utils/ServerSocket.js
This moves/commits the `brokenSignalDetectorOn` experiment previously running in PWA to jslib-media. It has been rolled out 100% for 1.5 months on PWA. It is used for faster client side disconnect detection, with a nice side effect of preventing most of the 5m periodic disconnects
A small change here is to turn on/off the noop keepalive loop when disconnected. And only apply it when using websockets (which we always do, but in case that changes...)
See also:
https://github.com/whereby/pwa/pull/3860
https://linear.app/whereby/issue/COB-187/decide-how-to-move-brokensignaldetectoron-from-experiment-to-feature
https://github.com/socketio/socket.io/issues/4868
<details>
<summary>📦 Published PR as canary version: <code>1.5.3--canary.41.7017285072.0</code></summary>
<br />
:sparkles: Test out …
=> Adds signal socket noop keepalive

package.json, src/utils/ReconnectManager.js, tests/utils/ReconnectManager.spec.js
This PR will fix state-keeping of remote clients in ReconnectManager.
Now it does not matter in what order information arrive in signal-server.
<details>
<summary>📦 Published PR as canary version: <code>1.5.4--canary.40.7018169839.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.5.4--canary.40.7018169839.0
yarn add @whereby/jslib-media@1.5.4--canary.40.7018169839.0
```
</details>
=> Fix state-keeping of remote clients in ReconnectManager

package.json, src/webrtc/BaseRtcManager.js, src/webrtc/P2pRtcManager.js, tests/webrtc/baseRtcManagerSpec.js
When reconnecting to signal-server, in P2P mode we don't send the `screenshare_started` request.
We do that in SFU mode.
This PR will listen for the `room_joined` response from signal-server and respond with a `screenshare_started` request if the client was screensharing when reconnecting. This will make P2P behave the same way as SFU.
1. `yarn run test:unit:coverage`
2. there should be decent test coverage for the change
Perform the test steps below using:
1. prod p2p room (should not be glitch-free on step 4 below)
2. prod sfu room (should be glitch-free)
3. pwa in local-dev mode using this canary release (should be glitch-free)
Steps to perform:
1. connect to room with tab A and tab B using `?glitchFreeOn` query param
2. start screenshare with tab A
3. force reconnect to signal-server …
=> Fix screenshare state for reconnecting p2p client

package.json, src/webrtc/stats/StatsMonitor/index.js
This renews compute pressure origin trials
<details>
<summary>📦 Published PR as canary version: <code>1.5.8--canary.47.7407031344.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.5.8--canary.47.7407031344.0
yarn add @whereby/jslib-media@1.5.8--canary.47.7407031344.0
```
</details>
=> Renews compute pressure tokens

.github/workflows/merge-main-workflow.yml, .github/workflows/pr-workflow.yml
We ran into a regression with the shared Github actions, as every dependent repo was just referencing @main and a breaking change was committed.
The breaking change has been reverted and the 1.0.0 tag has been added to ensure we dont run into this again.
<details>
<summary>📦 Published PR as canary version: <code>1.6.1--canary.49.7540204918.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.6.1--canary.49.7540204918.0
yarn add @whereby/jslib-media@1.6.1--canary.49.7540204918.0
```
</details>
=> Pin shared Github actions to 1.0.0

package.json, src/webrtc/stats/IssueMonitor/index.js
Remove `qualityLimitationReason === "bandwidth"` from the `bad-network` issue detection calculation.
This value takes a long-time to recover after e.g. high packet-loss has already ended.
<details>
<summary>📦 Published PR as canary version: <code>1.7.2--canary.53.7668924857.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.7.2--canary.53.7668924857.0
yarn add @whereby/jslib-media@1.7.2--canary.53.7668924857.0
```
</details>
=> Improve bad-network issue detector check

jest.config.js, package.json, src/utils/ipRegex.js, src/webrtc/P2pRtcManager.js, src/webrtc/RtcManagerDispatcher.js, src/webrtc/VegaRtcManager.js, src/webrtc/rtcStatsService.js, tests/webrtc/RtcManagerDispatcher.spec.js, tests/webrtc/VegaRtcManager.spec.js, yarn.lock
We need a custom device handler for Node clients using the Werift library. We don't know which handler works best (or whether we need to write our own to handle Node clients), so I think allowing the client to provide a handler is the easiest option.
It's a bit of a pain with the Node client still in development... Easiest with [yalc](https://github.com/wclr/yalc)
- clone [the browser sdk branch targeting this branch](https://github.com/whereby/browser-sdk/pull/171) and run `yarn build && yalc publish`
- clone [the node-sdk-test repo](https://github.com/whereby/node-sdk-test) and `yalc add @whereby.com/browser-sdk@2.0.0-beta3 && yarn`
- in that dir, add a room to .env like so:
```
ROOM_URL=https://team.whereby.com/%YOUR_ROOM%
ROOM_NAME=/%YOUR_ROOM%
```
- open your chosen room in a browser …
=> Allow explicit device handler factory

package.json, src/webrtc/stats/StatsMonitor/index.js
Compute pressure origin trial tokens has been renewed. same tokens as before, no need to deploy/publish
<details>
<summary>📦 Published PR as canary version: <code>1.7.6--canary.57.7841280852.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.7.6--canary.57.7841280852.0
yarn add @whereby/jslib-media@1.7.6--canary.57.7841280852.0
```
</details>
=> Compute pressure tokens updated

package.json, src/utils/ReconnectManager.js, src/webrtc/stats/IssueMonitor/index.js, src/webrtc/stats/StatsMonitor/metrics.js
<details>
<summary>📦 Published PR as canary version: <code>1.7.7--canary.68.7869334338.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.7.7--canary.68.7869334338.0
yarn add @whereby/jslib-media@1.7.7--canary.68.7869334338.0
```
</details>
=> Split distortion into concealment and acceleration/deacceleration

package.json, src/webrtc/P2pRtcManager.js
This reverses the offer/answer role when we fail to set local description from offer generated. We will run this as an experiment to see if it can help some users on buggy(?) devices/browsers.
<details>
<summary>📦 Published PR as canary version: <code>1.8.1--canary.69.7887303967.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.8.1--canary.69.7887303967.0
yarn add @whereby/jslib-media@1.8.1--canary.69.7887303967.0
```
</details>
=> Reverses offer/answer role on sld failure

.autorc.json, .eslintrc, config/eslint/browser.js, config/eslint/es6.js, package.json, yarn.lock
We are seeing some problems from our customers when installing our browser-sdk package. This is because we rely on some internal private repos for development.
Originially we thought this would not be an issue, but it seems like we were wrong. For now, copy the eslint config into this repo. This will most likely be short-lived, as we are planning to move this library into our new monorepo setup.
<details>
<summary>📦 Published PR as canary version: <code>1.9.1--canary.71.7929280079.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.1--canary.71.7929280079.0
yarn add @whereby/jslib-media@1.9.1--canary.71.7929280079.0
```
</details>
=> Remove internal devDependencies

package.json, src/webrtc/stats/IssueMonitor/index.js
This PR will:
1. add desync issue to stats
2. stop checking global issues/metrics for remote clients
<details>
<summary>📦 Published PR as canary version: <code>1.9.2--canary.70.7932506468.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.2--canary.70.7932506468.0
yarn add @whereby/jslib-media@1.9.2--canary.70.7932506468.0
```
</details>
=> Add desync issue to stats

package.json, src/webrtc/P2pRtcManager.js, src/webrtc/sdpModifier.js, tests/webrtc/sdpModifier.spec.js
Add RTP header extension abs-capture-time
https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-capture-time
<details>
<summary>📦 Published PR as canary version: <code>1.9.3--canary.55.7955959148.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.3--canary.55.7955959148.0
yarn add @whereby/jslib-media@1.9.3--canary.55.7955959148.0
```
</details>
=> Add RTP header extension abs-capture-time

package.json, yarn.lock
Canary package creation currently fails. There's a related issue in `auto`'s  repo (https://github.com/intuit/auto/issues/2432), they say this is fixed in the latest version.
This makes https://github.com/whereby/jslib-media/pull/81 and https://github.com/whereby/jslib-media/pull/76 dependabot PRs obsolete.
<details>
<summary>📦 Published PR as canary version: <code>1.9.5--canary.83.8050876351.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.5--canary.83.8050876351.0
yarn add @whereby/jslib-media@1.9.5--canary.83.8050876351.0
```
</details>
=> Update `auto` dependency

package.json, src/webrtc/mediaConstraints.js, tests/webrtc/mediaConstraints.spec.js
This flag was added here: https://github.com/whereby/jslib-media/pull/37
But now it is enabled for everyone, so it's value can be _hard coded_ and the option can be removed.
<details>
<summary>📦 Published PR as canary version: <code>1.9.6--canary.82.8062035262.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.6--canary.82.8062035262.0
yarn add @whereby/jslib-media@1.9.6--canary.82.8062035262.0
```
</details>
=> Remove fps24 option from getMediaConstraints

package.json
<details>
<summary>📦 Published PR as canary version: <code>1.9.7--canary.87.8137721964.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.7--canary.87.8137721964.0
yarn add @whereby/jslib-media@1.9.7--canary.87.8137721964.0
```
</details>
=> Bump version to 1.9.6 after updating deps

package.json, src/utils/ServerSocket.js, src/webrtc/P2pRtcManager.js, src/webrtc/Session.js, src/webrtc/VegaRtcManager.js, src/webrtc/bugDetector.js, src/webrtc/mediaConstraints.js, src/webrtc/rtcStatsService.js, src/webrtc/sdpModifier.js
There's a confusion in ESM and CJS, let's try to fix them by using `default` wrapper removal for `adapter` (as suggested here: https://github.com/reduxjs/redux-toolkit/issues/1960).
<details>
<summary>📦 Published PR as canary version: <code>1.9.8--canary.89.8267611592.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.8--canary.89.8267611592.0
yarn add @whereby/jslib-media@1.9.8--canary.89.8267611592.0
```
</details>
=> Fix adapter imports for sdk

package.json, src/webrtc/stats/StatsMonitor/index.js
Same tokens but renewed
<details>
<summary>📦 Published PR as canary version: <code>1.9.9--canary.91.8322937598.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.9--canary.91.8322937598.0
yarn add @whereby/jslib-media@1.9.9--canary.91.8322937598.0
```
</details>
=> Compute Pressure OT Tokens renewed

package.json, src/webrtc/MediaDevices.js, tests/webrtc/MediaDevices.spec.js, tests/webrtc/mediaConstraints.spec.js
<details>
<summary>📦 Published PR as canary version: <code>1.9.10--canary.92.8342626418.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@1.9.10--canary.92.8342626418.0
yarn add @whereby/jslib-media@1.9.10--canary.92.8342626418.0
```
</details>
=> Improve test coverage of media helper functions

README.md
Repo has moved, so update readme to point to new location
<details>
<summary>📦 Published PR as canary version: <code>2.0.1--canary.101.8448277685.0</code></summary>
<br />
```bash
npm install @whereby/jslib-media@2.0.1--canary.101.8448277685.0
yarn add @whereby/jslib-media@2.0.1--canary.101.8448277685.0
```
</details>
=> Update readme to indicate that the repo has moved
